### ISSUE TITLE
AD用户无法以流水线保存人身份执行流水

### ISSUE THREAD

**Issue by xujh0225** [ci-plugins/pushJobFile#3]
使用V1.0.3版本发布，AD用户仍旧无法以流水线保存人身份执行流水
![发布报错](https://user-images.githubusercontent.com/18331663/107135020-3d244300-6932-11eb-89e7-142db5348d47.jpg)

**Comment by jsonwan** [comment]
AD用户是指admin吗，需要确认下流水线保存人的账号在作业平台的系统中是否存在

**Comment by jsonwan** [comment]
![image](https://user-images.githubusercontent.com/53823124/108588721-9ad67780-7395-11eb-8eb9-ffab9519fb00.png)
图中这个邮箱地址是一个有效的用户名称吗

**Comment by xujh0225** [comment]
是的，windows的AD用户

**Comment by xujh0225** [comment]
是域用户名，不是admin本地用户

**Comment by xujh0225** [comment]
权限中心也已经给了作业平台的执行权限

**Comment by xujh0225** [comment]
现在情况如下：
1.  流水线用admin修改保存，AD用户可以正常运行。
2.  流水线用AD用户修改保存，AD用户执行就会报以上错误。

**Comment by jsonwan** [comment]
> 权限中心也已经给了作业平台的执行权限

确认下权限中心里是否给了fpm0204@fjt.com这个账号对应业务下的【快速分发文件】的权限，你提到的【执行权限】可能没对上。

**Comment by xujh0225** [comment]
作业平台的所有权限都给了。我理解，admin用户修改保存流程后，fpm0204@fjt.com可以正常执行程序，就说明是有权限的。
但fpm0204@fjt.com用户修改保存流程后，fpm0204@fjt.com用户执行就报权限错误。
![5](https://user-images.githubusercontent.com/18331663/108945429-8f39c800-7697-11eb-9520-212fdf2c390e.jpg)
![6](https://user-images.githubusercontent.com/18331663/108945446-952fa900-7697-11eb-8c31-768504749637.jpg)

**Comment by xujh0225** [comment]
如果方便，是否可以通过向日葵远程方式看下，更直观点呢?

**Comment by jsonwan** [comment]
插件是使用流水线最后保存人的身份去调用作业平台接口的。
admin用户保存后，无论是谁执行都是使用admin的身份去调用作业平台接口，能够执行只能说明admin这个账号有权限；
fpm0204@fjt.com用户保存后，无论是谁执行都是使用fpm0204@fjt.com的身份去调用作业平台接口，不能执行说明fpm0204@fjt.com这个账号没有权限；
需要在权限中心核实的是fpm0204@fjt.com这个账号有哪些权限，有没有包含作业平台的快速执行脚本权限，以及快速执行脚本权限关联的实例是否包含插件中指定的所有主机（建议关联实例资源选择任意主机），上面截的图没有把账号截出来，要看的是fpm0204@fjt.com这个账号的权限而不是admin账号的权限；
如果账号也确认了，fpm0204@fjt.com这个账号确实有权限了，需要检查下账号首尾是不是有多余的空格。

**Comment by xujh0225** [comment]
问题已经解决，的确是用户账号权限问题，谢谢！
